version: '3.8'

services:

  postgres:
    image: postgres:17.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

  app:
    build: .
    container_name: movies_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movies
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/movies
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
    ports:
      - "80:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
