-- Action Movies
insert into movies (id, title, release_date, poster_url, overview, genres, runtime_minutes, language,
                    rating_score,
                    rating_count)
-- Action Movies
values (1, 'Mad Max: Fury Road', '2015-05-15',
        'https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_.jpg',
        'A dystopian future where a warlord controls the water supply and a group of rebels fight to overthrow him.',
        'Action', 120, 'English', 8.1, 800000),
       (2, 'Die Hard', '1988-07-15', 'poster_url_here',
        'New York cop John McClane fights terrorists who have taken hostages in a Los Angeles skyscraper.',
        'Action',
        132, 'English', 8.2, 750000),
       (3, 'The Dark Knight', '2008-07-18', 'poster_url_here',
        'Batman must stop the Joker, a criminal mastermind who wants to create chaos in Gotham City.',
        'Action', 152,
        'English',
        9.0, 2200000),
       (4, 'John Wick', '2014-10-24', 'poster_url_here',
        'A retired hitman seeks vengeance on the men who killed his dog and stole his car.', 'Action', 101,
        'English',
        7.4,
        500000),

-- Adventure Movies
       (5, 'The Lord of the Rings: The Fellowship of the Ring', '2001-12-19', 'poster_url_here',
        'A young hobbit is tasked with destroying a powerful ring before it can fall into the hands of evil.',
        'Adventure', 178, 'English', 8.8, 1700000),
       (6, 'Indiana Jones: Raiders of the Lost Ark', '1981-06-12', 'poster_url_here',
        'Archaeologist Indiana Jones battles Nazis to recover a mystical artifact known as the Ark of the Covenant.',
        'Adventure', 115, 'English', 8.4, 800000),
       (7, 'Pirates of the Caribbean: The Curse of the Black Pearl', '2003-07-09', 'poster_url_here',
        'Captain Jack Sparrow teams up with a blacksmith to rescue a woman from cursed pirates.',
        'Adventure', 143,
        'English',
        8.0, 1000000),
       (8, 'The Hobbit: An Unexpected Journey', '2012-12-14', 'poster_url_here',
        'A young hobbit embarks on a journey to help a group of dwarves reclaim their kingdom from a dragon.',
        'Adventure', 169, 'English', 7.8, 700000),

-- Animation Movies
       (9, 'Toy Story 3', '2010-06-18', 'poster_url_here',
        'Woody, Buzz, and the rest of Andys toys face new challenges as they are donated to a daycare center.',
        'Animation', 103, 'English', 8.3, 700000),
       (10, 'Finding Nemo', '2003-05-30', 'poster_url_here',
        'A clownfish embarks on a journey to find his missing son, who was captured by a diver.',
        'Animation', 100,
        'English',
        8.1, 800000),
       (11, 'The Lion King', '1994-06-15', 'poster_url_here',
        'A young lion prince flees his kingdom only to return years later to reclaim his throne from his evil uncle.',
        'Animation', 88, 'English', 8.5, 1500000),
       (12, 'Shrek', '2001-04-22', 'poster_url_here',
        'An ogre embarks on a journey to rescue a princess, but finds love and friendship along the way.',
        'Animation',
        90, 'English', 7.9, 900000),

-- Biography Movies
       (13, 'The Theory of Everything', '2014-11-07', 'poster_url_here',
        'A look at the life of the famous physicist, Stephen Hawking, focusing on his early years, his relationship with his wife, and his groundbreaking work in theoretical physics.',
        'Biography', 123, 'English', 7.7, 800000),
       (14, 'Bohemian Rhapsody', '2018-11-02', 'poster_url_here',
        'The story of the rise to fame of the legendary rock band Queen, and its iconic lead singer, Freddie Mercury.',
        'Biography', 134, 'English', 8.0, 1400000),
       (15, 'The Pursuit of Happyness', '2006-12-15', 'poster_url_here',
        'A struggling salesman takes custody of his son as he’s poised to begin a life-changing professional career.',
        'Biography', 117, 'English', 8.0, 1500000),
       (16, 'A Beautiful Mind', '2001-12-21', 'poster_url_here',
        'The story of John Nash, a brilliant but asocial mathematician who struggles with schizophrenia.',
        'Biography',
        135, 'English', 8.2, 1300000),

-- Comedy Movies
       (17, 'The Hangover', '2009-06-05', 'poster_url_here',
        'A group of friends must retrace their steps after a bachelor party goes terribly wrong.', 'Comedy',
        100,
        'English',
        7.7, 700000),
       (18, 'Superbad', '2007-08-17', 'poster_url_here',
        'Two high school friends try to buy alcohol for a party in an attempt to impress their crushes.',
        'Comedy', 113,
        'English', 7.6, 600000),
       (19, 'Groundhog Day', '1993-02-12', 'poster_url_here',
        'A weatherman is forced to relive the same day over and over again until he learns important life lessons.',
        'Comedy', 101, 'English', 8.0, 600000),
       (20, 'The Big Lebowski', '1998-03-06', 'poster_url_here',
        'A laid-back man named "The Dude" gets caught up in a complex kidnapping case after being mistaken for a millionaire.',
        'Comedy', 117, 'English', 8.1, 500000),

-- Crime Movies
       (21, 'The Godfather', '1972-03-24', 'poster_url_here',
        'The aging patriarch of a crime dynasty transfers control of his clandestine empire to his reluctant son.',
        'Crime', 175, 'English', 9.2, 2500000),
       (22, 'Pulp Fiction', '1994-10-14', 'poster_url_here',
        'The lives of several individuals intertwine in a series of interwoven stories centered around crime and redemption.',
        'Crime', 154, 'English', 8.9, 1600000),
       (23, 'Goodfellas', '1990-09-19', 'poster_url_here',
        'The rise and fall of a young man in the mafia, following his life through the criminal world.',
        'Crime', 146,
        'English', 8.7, 1300000),
       (24, 'The Dark Knight', '2008-07-18', 'poster_url_here',
        'Batman battles the Joker, a criminal mastermind who seeks to create chaos in Gotham City.',
        'Crime', 152,
        'English',
        9.0, 2200000),

-- Documentary Movies
       (25, 'Wont You Be My Neighbor?', '2018-06-08', 'poster_url_here',
        'A documentary about the life and legacy of Fred Rogers, the beloved host of the popular childrens TV show "Mister Rogers Neighborhood".',
        'Documentary', 94, 'English', 8.4, 400000),
       (26, '13th', '2016-10-07', 'poster_url_here',
        'An in-depth look at the U.S. prison system and how it disproportionately affects African Americans.',
        'Documentary', 100, 'English', 8.2, 500000),
       (27, 'Free Solo', '2018-09-28', 'poster_url_here',
        'A documentary about rock climber Alex Honnold and his attempt to climb El Capitan without ropes.',
        'Documentary', 100, 'English', 8.0, 600000),
       (28, 'Jiro Dreams of Sushi', '2011-03-11', 'poster_url_here',
        'An 85-year-old sushi master strives for perfection in his work while his sons struggle to follow in his footsteps.',
        'Documentary', 81, 'English', 7.9, 300000),

-- Drama Movies
       (29, 'The Shawshank Redemption', '1994-09-22', 'poster_url_here',
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'Drama', 142, 'English', 9.3, 2200000),
       (30, 'Forrest Gump', '1994-07-06', 'poster_url_here',
        'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary life story.',
        'Drama', 142, 'English', 8.8, 2000000),
       (31, 'A Beautiful Mind', '2001-12-21', 'poster_url_here',
        'The story of John Nash, a brilliant but asocial mathematician who develops paranoid schizophrenia.',
        'Drama',
        135, 'English', 8.2, 600000),
       (32, 'The Pursuit of Happyness', '2006-12-15', 'poster_url_here',
        'A struggling salesman takes custody of his son as he battles with homelessness and his own troubled past.',
        'Drama', 117, 'English', 8.0, 900000),

-- Family Movies
       (33, 'The Lion King', '1994-06-15', 'poster_url_here',
        'A young lion prince flees his kingdom only to return years later to reclaim his throne from his evil uncle.',
        'Family', 88, 'English', 8.5, 1500000),
       (34, 'Toy Story 3', '2010-06-18', 'poster_url_here',
        'Woody, Buzz, and the rest of Andys toys face new challenges as they are donated to a daycare center.',
        'Family', 103, 'English', 8.3, 700000),
       (35, 'Finding Nemo', '2003-05-30', 'poster_url_here',
        'A clownfish embarks on a journey to find his missing son, who was captured by a diver.', 'Family',
        100,
        'English', 8.1, 800000),
       (36, 'Shrek', '2001-04-22', 'poster_url_here',
        'An ogre embarks on a journey to rescue a princess, but finds love and friendship along the way.',
        'Family', 90,
        'English', 7.9, 900000),

-- Fantasy Movies
       (37, 'Harry Potter and the Sorcerers Stone', '2001-11-10', 'poster_url_here',
        'A young boy discovers he is a wizard and begins his education at the Hogwarts School of Witchcraft and Wizardry.',
        'Fantasy', 152, 'English', 7.9, 1500000),
       (38, 'The Lord of the Rings: The Return of the King', '2003-12-17', 'poster_url_here',
        'The hobbit Frodo Baggins and his companions continue their quest to destroy the One Ring in the fires of Mount Doom.',
        'Fantasy', 201, 'English', 8.9, 1600000),
       (39, 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', '2005-12-09',
        'poster_url_here',
        'Four siblings discover a magical land through an enchanted wardrobe and join the fight to defeat an evil White Witch.',
        'Fantasy', 143, 'English', 6.9, 700000),
       (40, 'Alice in Wonderland', '2010-03-05', 'poster_url_here',
        'A young woman returns to the magical world from her childhood, where she reunites with her friends and learns of her destiny.',
        'Fantasy', 108, 'English', 6.4, 600000),

-- History Movies
       (41, 'Gladiator', '2000-05-05', 'poster_url_here',
        'A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.',
        'History', 155, 'English', 8.5, 1300000),
       (42, 'Schindlers List', '1993-12-15', 'poster_url_here',
        'In Nazi-occupied Poland during World War II, businessman Oskar Schindler saves the lives of over a thousand Jewish refugees by employing them in his factory.',
        'History', 195, 'English', 9.0, 2000000),
       (43, 'The Last Samurai', '2003-12-05', 'poster_url_here',
        'An American military officer is hired to train the Japanese army in modern warfare, but he ends up becoming a part of the Samurai culture.',
        'History', 154, 'English', 7.7, 600000),
       (44, 'Braveheart', '1995-05-24', 'poster_url_here',
        'A Scottish warrior leads his countrymen in a rebellion to free his homeland from the rule of King Edward I of England.',
        'History', 178, 'English', 8.3, 1500000),

-- Horror Movies
       (45, 'The Shining', '1980-05-23', 'poster_url_here',
        'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrifying visions.',
        'Horror', 146, 'English', 8.4, 600000),
       (46, 'It', '2017-09-08', 'poster_url_here',
        'A group of bullied kids band together to destroy a shape-shifting monster that poses as a child-eating clown.',
        'Horror', 135, 'English', 7.3, 800000),
       (47, 'Get Out', '2017-02-24', 'poster_url_here',
        'A young African-American man visits his white girlfriends parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
        'Horror', 104, 'English', 7.7, 700000),
       (48, 'A Nightmare on Elm Street', '1984-11-09', 'poster_url_here',
        'Teenagers in a small town are being stalked and killed in their dreams by a man with a burned face and knife-tipped gloves.',
        'Horror', 91, 'English', 7.5, 800000),

-- Musical Movies
       (49, 'Whiplash', '2014-10-10', 'poster_url_here',
        'A promising young drummer enrolls at a prestigious music conservatory, where an abusive instructor pushes him to the limit.',
        'Musical', 106, 'English', 8.5, 800000),
       (50, 'La La Land', '2016-12-09', 'poster_url_here',
        'A jazz musician and an aspiring actress fall in love but struggle to maintain their relationship as they pursue their individual dreams.',
        'Musical', 128, 'English', 8.0, 800000),
       (51, 'A Star is Born', '2018-10-05', 'poster_url_here',
        'A seasoned musician helps a young singer find fame, even as age and alcoholism send his own career into a downward spiral.',
        'Musical', 136, 'English', 7.6, 500000),
       (52, 'The Sound of Music', '1965-03-02', 'poster_url_here',
        'A young aspiring nun is sent to be the governess for a widowed naval captains seven children and brings joy into their lives.',
        'Musical', 174, 'English', 8.0, 400000),

-- Mystery Movies
       (53, 'The Girl with the Dragon Tattoo', '2011-12-20', 'poster_url_here',
        'A journalist and a hacker uncover a dark family secret while investigating a wealthy businessmans missing niece.',
        'Mystery', 158, 'English', 7.8, 600000),
       (54, 'Shutter Island', '2010-02-19', 'poster_url_here',
        'A U.S. Marshal investigates the disappearance of a patient from a hospital for the criminally insane, but uncovers shocking secrets.',
        'Mystery', 138, 'English', 8.2, 800000),
       (55, 'The Sixth Sense', '1999-08-06', 'poster_url_here',
        'A troubled young boy who communicates with spirits that dont know they are dead seeks the help of a disheartened child psychologist.',
        'Mystery', 107, 'English', 8.1, 1000000),
       (56, 'Gone Girl', '2014-10-03', 'poster_url_here',
        'A man becomes the prime suspect in the disappearance of his wife, leading to a media frenzy and mysterious events.',
        'Mystery', 149, 'English', 8.1, 900000),

-- Noir Movies
       (57, 'Double Indemnity', '1944-05-11', 'poster_url_here',
        'An insurance salesman and a femme fatale plot to murder her husband and collect the insurance money, but things dont go as planned.',
        'Noir', 107, 'English', 8.3, 400000),
       (58, 'The Big Sleep', '1946-08-23', 'poster_url_here',
        'A private detective is hired to investigate the case of a wealthy family and uncovers a web of deception, murder, and corruption.',
        'Noir', 114, 'English', 8.0, 300000),
       (59, 'Chinatown', '1974-06-20', 'poster_url_here',
        'A private detective investigates a wealthy land developer’s wife’s infidelity but finds himself tangled in a complex case involving corruption, water rights, and murder.',
        'Noir', 130, 'English', 8.2, 900000),
       (60, 'L.A. Confidential', '1997-09-19', 'poster_url_here',
        'Three policemen in 1950s Los Angeles investigate a series of interconnected crimes, uncovering corruption and scandal at every turn.',
        'Noir', 138, 'English', 8.2, 1100000),

-- Psychological Movies
       (61, 'Black Swan', '2010-12-03', 'poster_url_here',
        'A dancer struggles with her mental health and a fierce rivalry as she prepares for a lead role in a New York City ballet production of Swan Lake.',
        'Psychological', 108, 'English', 8.0, 700000),
       (62, 'Fight Club', '1999-10-15', 'poster_url_here',
        'An insomniac office worker forms an underground fight club with a soap salesman, leading to a dangerous descent into anarchy and self-destruction.',
        'Psychological', 139, 'English', 8.8, 2000000),
       (63, 'Shutter Island', '2010-02-19', 'poster_url_here',
        'A U.S. Marshal investigates the disappearance of a patient from a mental hospital, uncovering disturbing secrets and questioning his own sanity.',
        'Psychological', 138, 'English', 8.2, 700000),
       (64, 'The Machinist', '2004-10-22', 'poster_url_here',
        'A factory worker suffering from severe insomnia begins to doubt his own sanity as he becomes increasingly paranoid about a series of strange occurrences.',
        'Psychological', 101, 'English', 7.7, 400000),

-- Romance Movies
       (65, 'The Notebook', '2004-06-25', 'poster_url_here',
        'A young couple falls in love during the early years of World War II, but their romance faces trials of time and memory.',
        'Romance', 123, 'English', 7.8, 800000),
       (66, 'Titanic', '1997-12-19', 'poster_url_here',
        'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
        'Romance', 195, 'English', 7.8, 2300000),
       (67, 'Pride and Prejudice', '2005-11-11', 'poster_url_here',
        'Sparks fly when spirited Elizabeth Bennet meets single, rich, and arrogant Mr. Darcy.', 'Romance',
        129,
        'English', 7.8,
        500000),
       (68, 'La La Land', '2016-12-09', 'poster_url_here',
        'A jazz musician and an aspiring actress fall in love but struggle to maintain their relationship as they pursue their individual dreams.',
        'Romance', 128, 'English', 8.0, 800000),

-- Sci-Fi Movies
       (69, 'Inception', '2010-07-16', 'poster_url_here',
        'A skilled thief is given a chance at redemption if he can successfully perform an inception—implanting an idea into someones mind.',
        'SciFi', 148, 'English', 8.8, 2000000),
       (70, 'Interstellar', '2014-11-07', 'poster_url_here',
        'A team of explorers travels through a wormhole in space in an attempt to ensure humanitys survival.',
        'SciFi',
        169, 'English', 8.6, 1300000),
       (71, 'The Matrix', '1999-03-31', 'poster_url_here',
        'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        'SciFi', 136, 'English', 8.7, 1800000),
       (72, 'Star Wars: Episode IV - A New Hope', '1977-05-25', 'poster_url_here',
        'Luke Skywalker embarks on a journey to rescue a princess and help defeat the evil Empire.',
        'SciFi', 121,
        'English',
        8.6, 2200000),

-- Sport Movies
       (73, 'Rocky', '1976-11-21', 'poster_url_here',
        'A small-time boxer gets a once-in-a-lifetime chance to fight the heavy-weight champion of the world in a bout that proves to be a fight for his dignity.',
        'Sport', 120, 'English', 8.1, 1500000),
       (74, 'The Blind Side', '2009-11-20', 'poster_url_here',
        'The true story of a homeless African-American teenager who is taken in by a wealthy family and becomes an All-American football player.',
        'Sport', 129, 'English', 7.6, 800000),
       (75, 'Moneyball', '2011-09-23', 'poster_url_here',
        'The true story of how the Oakland Athletics used unconventional methods and statistics to build a competitive baseball team on a small budget.',
        'Sport', 133, 'English', 7.6, 900000),
       (76, 'Chariots of Fire', '1981-05-15', 'poster_url_here',
        'The true story of two British athletes competing in the 1924 Olympics, who must overcome personal and professional obstacles to achieve their dreams.',
        'Sport', 125, 'English', 7.2, 500000),

-- Superhero Movies
       (77, 'The Dark Knight', '2008-07-18', 'poster_url_here',
        'Batman faces the Joker, a criminal mastermind who seeks to plunge Gotham City into anarchy, testing the limits of justice and morality.',
        'Superhero', 152, 'English', 9.0, 2200000),
       (78, 'Avengers: Endgame', '2019-04-26', 'poster_url_here',
        'The Avengers assemble to take on the most powerful being in the universe, Thanos, in a battle to undo the destruction caused by him in "Infinity War."',
        'Superhero', 181, 'English', 8.4, 2500000),
       (79, 'Spider-Man: Into the Spider-Verse', '2018-12-14', 'poster_url_here',
        'Teenager Miles Morales is thrust into the role of Spider-Man and must team up with other Spider-People from different dimensions to stop a threat that could destroy all realities.',
        'Superhero', 117, 'English', 8.4, 700000),
       (80, 'Iron Man', '2008-05-02', 'poster_url_here',
        'Tony Stark, a billionaire genius, is captured by terrorists and forced to build a weapon of mass destruction, but instead builds a suit of armor to escape and fight back.',
        'Superhero', 126, 'English', 7.9, 1800000),

-- Thriller Movies
       (81, 'The Silence of the Lambs', '1991-02-14', 'poster_url_here',
        'A young FBI agent seeks the help of a cannibalistic serial killer to apprehend another murderer on the loose.',
        'Thriller', 118, 'English', 8.6, 1300000),
       (82, 'Se7en', '1995-09-22', 'poster_url_here',
        'A detective and his rookie partner hunt a serial killer who uses the seven deadly sins as his modus operandi.',
        'Thriller', 127, 'English', 8.6, 1300000),
       (83, 'Fight Club', '1999-10-15', 'poster_url_here',
        'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much more.',
        'Thriller', 139, 'English', 8.8, 1500000),
       (84, 'Gone Girl', '2014-10-03', 'poster_url_here',
        'A man becomes the prime suspect in the disappearance of his wife, leading to a media frenzy and mysterious events.',
        'Thriller', 149, 'English', 8.1, 900000),

-- War Movies
       (85, 'Saving Private Ryan', '1998-07-24', 'poster_url_here',
        'A group of U.S. soldiers is sent to find and bring home a paratrooper whose brothers have been killed in action during WWII.',
        'War', 169, 'English', 8.6, 1500000),
       (86, 'Apocalypse Now', '1979-08-15', 'poster_url_here',
        'During the Vietnam War, Captain Willard is assigned to assassinate a rogue colonel who has gone insane and is waging his own war in Cambodia.',
        'War', 153, 'English', 8.4, 800000),
       (87, 'Full Metal Jacket', '1987-06-26', 'poster_url_here',
        'A private goes through basic training to become a Marine and ultimately experiences the horrors of the Vietnam War.',
        'War', 116, 'English', 8.3, 700000),
       (88, '1917', '2019-12-25', 'poster_url_here',
        'Two British soldiers must deliver a message to save 1600 men during World War I.', 'War', 119,
        'English', 8.3,
        800000),

-- Western Movies
       (89, 'The Good, the Bad and the Ugly', '1966-12-23', 'poster_url_here',
        'A bounty hunter, a Mexican bandit, and a Confederate soldier search for a cache of gold during the American Civil War.',
        'Western', 161, 'English', 8.8, 700000),
       (90, 'Once Upon a Time in the West', '1968-12-23', 'poster_url_here',
        'A mysterious stranger and a notorious outlaw team up to protect a widow from a ruthless assassin who is working for the railroad.',
        'Western', 165, 'English', 8.5, 600000),
       (91, 'Unforgiven', '1992-08-07', 'poster_url_here',
        'A retired gunslinger is forced to take on one last job in order to gain justice for a murdered prostitute.',
        'Western', 131, 'English', 8.2, 500000),
       (92, 'The Searchers', '1956-03-03', 'poster_url_here',
        'A Civil War veteran spends years searching for his niece who was kidnapped by a Native American tribe.',
        'Western', 119, 'English', 8.0, 400000);